export const SECTION_SELECTORS = `.section,
section,
article,
aside,
.article,
.id-Teaser-el,
.teaser,
figure,
.hs-widget,
.sz-teaserlist-element,
.szFussballTickerTeasermodul,
.teaser-media,
.thema_clip_large [role="region"],
.park-opener,
.pdb-teaser,
.pdb-teaser3-row-item,
[role="listitem"],
.hcf-ressort,
.promo,
.clearfix,
.info,
.o-teaser,
.vhb-teaser,
.zg-kickerticker
`;
